AllCops:
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
   Enabled: False
